baseurl = "https://athishsreeram.github.io/dreamworks/"
languageCode = "en-US"
title = "Dreamworks"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.png"
  author = "Athishsreeram Nharayanan"
  description = "Dreamworks"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "athishsreeram"
  Email         = "athishsreeram007@gmail.com"
  Twitter       = "athish77303993"
  LinkedIn      = "athishsreeram-nharayanan-1a47911b"
  Stackoverflow = "athish-sreeram"
 
## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/resume/"
